name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtserialport'

    - name: Configure
      run: |
        if (Test-Path build) {
          Remove-Item -Recurse -Force build
        }
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Deploy
      run: |
        if (Test-Path deploy) {
          Remove-Item -Recurse -Force deploy
        }
        mkdir deploy
        copy build\Release\asdKeypad_cpp.exe deploy\
        windeployqt --no-translations deploy\asdKeypad_cpp.exe
        # Copy Visual C++ Runtime files
        copy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\14.29.30133\x64\Microsoft.VC142.CRT\*" deploy\

    - name: Create ZIP
      run: |
        Compress-Archive -Path deploy\* -DestinationPath asdKeypad_windows_x64.zip -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: asdKeypad_windows_x64
        path: asdKeypad_windows_x64.zip